server:
    port: @port@

spring:
    datasource:
        url: jdbc:mysql://@database_host@:@database_port@/@database_name@?serverTimezone=Europe/Paris
        username: @database_user@
        password: @database_password@
        driver-class-name: com.mysql.jdbc.Driver
    
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        generate-ddl: true
        hibernate:
            ddl-auto: @ddlauto@