server:
    port: 3000
    forward-headers-strategy: NATIVE
    servlet:
        encoding:
            force-response: true
            charset: UTF-8
spring:
    datasource:
        url: jdbc:mysql://database:3306/polyflow
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver

    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
        generate-ddl: true
        hibernate:
            ddl-auto: update
    main:
        allow-bean-definition-overriding: true
env:
    mode: test
security:
    active: true

servers:
    student_api:
        host: pf-students
        port: 4000
    front:
        host: front
        port: 4200
