version: "2.1"

services:
  database:
    container_name: database
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'polyflow'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    expose:
      - "3307"
    ports: 
      - "3307:3306"
  pf-system:
    image: polyflow/back-end
    container_name: pf-system
    build: 
      context: ..
      dockerfile: ./docker/system/Dockerfile
    expose:
      - "3000"
    ports:
      - "3000:8080"
    depends_on: 
      - database
      - pf-students
  pf-students:
    image: polyflow/students
    container_name: pf-students
    build: 
      context: ..
      dockerfile: ./docker/students/Dockerfile
    expose:
      - "4000"
    ports:
      - "4000:4000"