package fr.polytech.wish.errors;

public enum WishErrorStatus {
    CONSTRAINT_NOT_RESPECTED,
    CONFLICT_COURSE,
    COURSE_ALREADY_MANDATORY,
    OPTINAL_COURSE_FULL,
    WISH_NOT_EDITABLE,
    NOT_ENOUGH_COURSES, 
    MINOR_NOT_SPECIFIED, 
    SANDWICH_COURSE_NOT_SPECIFIED, CANCELLABLE_NOT_CHOOSEN, CANCELLABLE_NOT_SANDWICH
}
